name: Go CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: 1.18

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - uses: dominikh/staticcheck-action@v1.3.1
      with:
        # renovate: datasource=go depName=honnef.co/go/tools/cmd/staticcheck
        version: "2023.1.7"

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...

    #- name: Run tests
    #  run: go test -race -vet=off ./...
